export const SUPPORTED_LANGUAGES = {
  gb: 'English',
  es: 'Español',
  de: 'Deutsch',
  fr: 'Français',
  it: 'Italiano',
  pt: 'Português',
  ru: 'Русский',
  zh: '中文',
  ja: '日本語',
  ko: '한국어',
  ar: 'العربية',
  hi: 'हिन्दी',
  tr: 'Türkçe',
  nl: 'Nederlands',
  pl: 'Polski',
  sv: 'Svenska',
  cs: 'Čeština',
  da: 'Dansk',
  fi: 'Suomi',
  hu: 'Magyar',
  no: 'Norsk',
  ro: 'Română',
  sk: 'Slovenčina',
  th: 'ไทย',
  vi: 'Tiếng Việt',
  el: 'Ελληνικά',
  bg: 'Български',
  et: 'Eesti',
  lt: 'Lietuvių'
}
export const AUTO_LANGUAGE = 'auto'
